### PR TITLE
Fix a bug on IPad

### PR DESCRIPTION
**Pull request by Canu667**
There was an error on IPad, when doing apply with the JQuery object

### CODE REVIEW

**Comment by eisbehr-** [comment]
Hello @Canu667 

Thanks for your pull request. Looks good so far. I would like to verify this problem by myself before merge. Could you please tell me how you hot this problem? Is it on iOS Safari? jQuery or jQuery mobile? Wich versions of jQuery and Lazy?

Thanks a lot!

**Comment by Canu667** [comment]
Hi,

Great to hear from you! I got this problem in work. It was an IPad first
generation and it appeared only on Safari - I think it is somehow connected
to the iOS version. I will try to get more details on monday.
I know that on newer IPads this problem does not exist.

Best regards,

2015-11-14 19:01 GMT+01:00 Eisbehr <notifications@github.com>:

**Comment by eisbehr-** [comment]
It's okay. Never noticed or heard the problem before. So a day more or less will be fine. ;)
Thanks!

**Comment by Canu667** [comment]
Yes, I haven't heard about it either, but one of my colleagues found it. I could not find any emulator, on which I could reproduce the issue, but still I have this 'lucky' IPad in front of me. I gathered all information about it below:

User agent:
UserAgent: Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/(B206 Safari/7534.48.3

iOS 5.1.1
Model MC497B

Regards,
Mateusz

**Comment by eisbehr-** [comment]
Hello @Canu667 

Thank your for give me some more details! I got an old iPad by my own and will check this. Could you just please tell me wich type (normal or modile) and version of jQuery the page, where the error occures, uses?

Thanks a lot for your support!

**Comment by Canu667** [comment]
Yes. it was jQuery 1.11.0

**Comment by eisbehr-** [comment]
Merged you change! Thanks for your support!

**Pull request merged**
