### PR TITLE
Use svg instead of png to get better image quality

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by eisbehr-** [comment]
Well, I like the png. ;)
I don't like the possibe security impact using svg.

**Comment by PeterDaveHello** [comment]
Any reference of the security issue? I don't think png will be safer. And we have https, GitHub will also pre-handle the images.

**Comment by eisbehr-** [comment]
It may be my personal problem with svg, but so they are client rendered there are always security questions. The a look here for some examples what i mean: https://www.hackinparis.com/talk-forbidden-image-svg

**Comment by PeterDaveHello** [comment]
Thanks,

**Pull request closed without merging**
